---
language: ruby
rvm:
  - 2.1.0
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
before_script:
  - bundle exec rake db:setup
script:
  - bundle exec rake test && bundle exec rake qunit:test
